### ISSUE TITLE
老哥，在CoordinatorLayout+AppBarLayout+Toolbar使用有点问题

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/StatusBar#1]
我想让状态栏透明，文字黑色，在toolbar上方时候是和toolbar背景色一致的，当toolbar折叠的时候只能看到状态栏的文字，toolbar隐藏，就是我原来做的下面视频中的效果，但是是用的window.addFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS)还要给toolbar写死顶部边距，用了你的库之后会是后面两张图上的效果，第一个就只是设置了immersive(toolbar)，第二个是另外设置了android:statusBarColor和android:windowLightStatusBar的🤔

https://user-images.githubusercontent.com/54784104/148235284-f9af4112-b7b3-4da8-96ff-26e5d9f44a7b.mp4
![微信图片_20220105223134](https://user-images.githubusercontent.com/54784104/148235344-b02d5502-e778-4975-bcca-629b7eeb2077.jpg)
![微信图片_20220105223128](https://user-images.githubusercontent.com/54784104/148235367-09f5e238-64ff-411d-87a5-5a4a370ee6cd.jpg)

**Comment by liangjingkanji** [comment]
immersive()的第一个参数是状态栏颜色, 如果是view则会提取其背景颜色. 第二个参数是状态栏文字颜色

我不清楚你的toolbar的背景颜色是什么?

```kotlin
immersive(Color.TRANSPARENT, true) // 设置状态栏颜色为透明, 文字颜色为黑色
toolbar.statusPadding() // 状态栏设置一个paddingTop为状态栏高度, 避免和状态栏重叠
```

**Comment by SaltedFish-Extreme** [comment]
> immersive()的第一个参数是状态栏颜色, 如果是view则会提取其背景颜色. 第二个参数是状态栏文字颜色
> 
> 我不清楚你的toolbar的背景颜色是什么?
> 
> ```kotlin
> immersive(Color.TRANSPARENT, true) // 设置状态栏颜色为透明, 文字颜色为黑色
> toolbar.statusPadding() // 状态栏设置一个paddingTop为状态栏高度, 避免和状态栏重叠
> ```

啊，我是用setSupportActionBar(toolBar)来设置toolbar的，背景色应该就是主题里的主要颜色，刚才用你的这两行代码设置后和我原来的效果基本一致了，就是statusPadding边距有点大了😂滚动自动显示toolbar时状态栏和toolbar会重叠， 我是直接把顶部边距和内边距写死的😢
````xml
app:layout_scrollFlags="scroll|enterAlways|snap"
android:layout_marginTop="5dp"
android:paddingTop="5dp"
````
![微信图片_20220106090955](https://user-images.githubusercontent.com/54784104/148311987-f937ed61-c8f4-4841-a1bd-22705af8a268.jpg)  

![微信图片_20220106091004](https://user-images.githubusercontent.com/54784104/148312024-36b700ff-2a1d-4f87-a430-444643fd6199.jpg)

**Comment by SaltedFish-Extreme** [comment]
总体来说老哥你的这个库是没啥问题的，不设置自动滚动显示隐藏toolbar的话，重叠一点也没啥问题，反正能滚动到完全显示toolbar，像我这样要在主题里设置状态栏颜色透明还有窗口状态栏日间模式，在activity里得设置窗口扩展到屏幕外，还得给toolbar设置顶部和内边距😂

**Comment by liangjingkanji** [comment]
"滚动自动显示toolbar时状态栏和toolbar会重叠", 这就是透明状态栏正常情况. 如果你不想就直接设置状态栏为指定颜色(非透明)

**Comment by SaltedFish-Extreme** [comment]
> "滚动自动显示toolbar时状态栏和toolbar会重叠", 这就是透明状态栏正常情况. 如果你不想就直接设置状态栏为指定颜色(非透明)

啊，我的意思是滚动自动显示toolbar时候状态栏会紧挨着toolbar有一点遮挡，然后还能继续拉一点，让状态栏跟toolbar隔开距离，就是那个边距的问题了，我是给写死了margintop属性，让状态栏和toolbar有一点距离

**Comment by liangjingkanji** [comment]
不太清楚你的描述, 你录个视频我看下什么错误

**Comment by SaltedFish-Extreme** [comment]
> 不太清楚你的描述, 你录个视频我看下什么错误

https://user-images.githubusercontent.com/54784104/148328775-4f0464ac-f61c-4b8c-8d48-beefb3a15194.mp4

**Comment by liangjingkanji** [comment]
这不是很正常吗? 

你的需求是用户在滑动过程中手势停止时候不被状态栏遮挡吧, 你应该给CoordinatorLayout下面的组件设置snap属性

**Comment by SaltedFish-Extreme** [comment]
> 这不是很正常吗?
> 
> 你的需求是用户在滑动过程中手势停止时候不被状态栏遮挡吧, 你应该给CoordinatorLayout下面的组件设置snap属性

还有刚滚动到显示toolbar时，右边的菜单按钮弹出菜单框会遮挡住状态栏（还有老哥，github我是真的连不上了，梯子都挂了，回复都得刷新半天😂）
![image](https://user-images.githubusercontent.com/54784104/148331023-c5427275-ae32-47f7-a2d7-a100642789b5.png)

**Comment by liangjingkanji** [comment]
这种用户主动滑动到一半被遮挡是正常情况. 透明状态栏都这样. 不然你觉得既不能遮挡又要透明那怎么显示
你设置snap属性才是解决方案

**Comment by SaltedFish-Extreme** [comment]
> 这种用户主动滑动到一半被遮挡是正常情况. 透明状态栏都这样. 不然你觉得既不能遮挡又要透明那怎么显示 你设置snap属性才是解决方案

啊，是这样，我一开始也设置了snap属性
````xml
app:layout_scrollFlags="scroll|enterAlways|snap"
````
就是断在中间会剩一些边距😂  

这样也挺好的了，麻烦老哥了😉

**Comment by liangjingkanji** [comment]
有问题再讨论
