### ISSUE TITLE
功能有点简陋,在fragment和dialog中无法使用

### ISSUE THREAD

**Issue by 424385117** [liangjingkanji/StatusBar#4]

**Comment by liangjingkanji** [comment]
说实话你这个提问让我有点无语, 你在fragment里面获取activity引用然后使用不就好了

**Comment by 424385117** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 424385117** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
